version: '3.3'

networks:
  rede:
    driver: bridge



services:
  db:
    build: 
      context: banco-de-dados
      dockerfile: ./Dockerfile
    container_name: container-bd
    ports:
      - "3306:3306"
    image: imagem-mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./config/db.env
    restart: always
    networks:
      - rede

  aplicacao:
    depends_on:
      - db
    build: 
      context: aplicacao
      dockerfile: ./Dockerfile
    image: imagem-php:latest
    container_name: container-php
    ports:
      - "80:80"

    networks:
      - rede

volumes:
  db_data: {}
