# Use a imagem oficial do Nginx como a imagem base
FROM nginx:latest

# Copie o arquivo de configuração personalizado para dentro do contêiner
COPY index.html /usr/share/nginx/html/index.html

# Exponha a porta 80 para permitir o acesso ao servidor web
EXPOSE 80
